name: mlModelRunner
on: 
    workflow_dispatch:    
    

jobs:
    echo:
        runs-on: self-hosted
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: |
                sudo chmod 666 /var/run/docker.sock
                ls
                
            - name: build image
              run: docker build . -t number1
            - name: docker run
              run: |
                docker run number1
                docker ps